//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.225
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.225.
// 
#pragma warning disable 1591

namespace Cliente.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerAreaCirculoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerAreaTrianguloOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerAreaCuadradoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::Cliente.Properties.Settings.Default.Cliente_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerAreaCirculoCompletedEventHandler ObtenerAreaCirculoCompleted;
        
        /// <remarks/>
        public event ObtenerAreaTrianguloCompletedEventHandler ObtenerAreaTrianguloCompleted;
        
        /// <remarks/>
        public event ObtenerAreaCuadradoCompletedEventHandler ObtenerAreaCuadradoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerAreaCirculo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double ObtenerAreaCirculo(double radio) {
            object[] results = this.Invoke("ObtenerAreaCirculo", new object[] {
                        radio});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerAreaCirculoAsync(double radio) {
            this.ObtenerAreaCirculoAsync(radio, null);
        }
        
        /// <remarks/>
        public void ObtenerAreaCirculoAsync(double radio, object userState) {
            if ((this.ObtenerAreaCirculoOperationCompleted == null)) {
                this.ObtenerAreaCirculoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerAreaCirculoOperationCompleted);
            }
            this.InvokeAsync("ObtenerAreaCirculo", new object[] {
                        radio}, this.ObtenerAreaCirculoOperationCompleted, userState);
        }
        
        private void OnObtenerAreaCirculoOperationCompleted(object arg) {
            if ((this.ObtenerAreaCirculoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerAreaCirculoCompleted(this, new ObtenerAreaCirculoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerAreaTriangulo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double ObtenerAreaTriangulo(double b, double a) {
            object[] results = this.Invoke("ObtenerAreaTriangulo", new object[] {
                        b,
                        a});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerAreaTrianguloAsync(double b, double a) {
            this.ObtenerAreaTrianguloAsync(b, a, null);
        }
        
        /// <remarks/>
        public void ObtenerAreaTrianguloAsync(double b, double a, object userState) {
            if ((this.ObtenerAreaTrianguloOperationCompleted == null)) {
                this.ObtenerAreaTrianguloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerAreaTrianguloOperationCompleted);
            }
            this.InvokeAsync("ObtenerAreaTriangulo", new object[] {
                        b,
                        a}, this.ObtenerAreaTrianguloOperationCompleted, userState);
        }
        
        private void OnObtenerAreaTrianguloOperationCompleted(object arg) {
            if ((this.ObtenerAreaTrianguloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerAreaTrianguloCompleted(this, new ObtenerAreaTrianguloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerAreaCuadrado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double ObtenerAreaCuadrado(double lado) {
            object[] results = this.Invoke("ObtenerAreaCuadrado", new object[] {
                        lado});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerAreaCuadradoAsync(double lado) {
            this.ObtenerAreaCuadradoAsync(lado, null);
        }
        
        /// <remarks/>
        public void ObtenerAreaCuadradoAsync(double lado, object userState) {
            if ((this.ObtenerAreaCuadradoOperationCompleted == null)) {
                this.ObtenerAreaCuadradoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerAreaCuadradoOperationCompleted);
            }
            this.InvokeAsync("ObtenerAreaCuadrado", new object[] {
                        lado}, this.ObtenerAreaCuadradoOperationCompleted, userState);
        }
        
        private void OnObtenerAreaCuadradoOperationCompleted(object arg) {
            if ((this.ObtenerAreaCuadradoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerAreaCuadradoCompleted(this, new ObtenerAreaCuadradoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerAreaCirculoCompletedEventHandler(object sender, ObtenerAreaCirculoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerAreaCirculoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerAreaCirculoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerAreaTrianguloCompletedEventHandler(object sender, ObtenerAreaTrianguloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerAreaTrianguloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerAreaTrianguloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerAreaCuadradoCompletedEventHandler(object sender, ObtenerAreaCuadradoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerAreaCuadradoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerAreaCuadradoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591